# Generated by Django 3.1.2 on 2020-11-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLng', models.FloatField()),
                ('startLat', models.FloatField()),
                ('endLng', models.FloatField()),
                ('endLat', models.FloatField()),
            ],
        ),
    ]
